const config=window.LEZHA_CONTENT||{};
const menu=document.querySelector('.menu-btn'),nav=document.querySelector('.nav');menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open))});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false')}));
const filters=document.querySelectorAll('.filter');filters.forEach(button=>button.addEventListener('click',()=>{const selected=button.dataset.filter;filters.forEach(item=>{const active=item===button;item.classList.toggle('active',active);item.setAttribute('aria-pressed',String(active))});document.querySelectorAll('.place').forEach(place=>{place.hidden=selected!=='all'&&place.dataset.category!==selected})}));
const selectors={histori:['.story-copy h2','.story-copy > p:not(.editorial-note)'],arkeologji:['#arkeologji h2','#arkeologji .section-top>p'],webgis:['#webgis h2','#webgis .section-top>p'],shkenca:['#shkenca h2','#shkenca .section-top>p'],kulinari:['#kulinari h2','#kulinari>div:first-child>p:first-of-type'],partneret:['#partneret h2','#partneret .section-top>p']};
Object.entries(config.sections||{}).forEach(([id,data])=>{const section=document.getElementById(id),target=selectors[id];if(!section||!target)return;section.hidden=data.visible===false;if(data.title)document.querySelector(target[0]).textContent=data.title;if(data.text)document.querySelector(target[1]).textContent=data.text;document.querySelectorAll('a[href="#'+id+'"]').forEach(a=>a.hidden=data.visible===false)});
const details={kalaja:{tag:'TRASHËGIMI HISTORIKE',title:'Kalaja e Lezhës',text:'Kalaja ndodhet mbi qytet dhe përfshin struktura e mure nga periudha të ndryshme. Pozicioni i saj e bën të dukshme lidhjen ndërmjet monumentit, Lezhës dhe peizazhit përreth.',source:'https://lezhaturistike.wordpress.com/vizito/'},akrolisi:{tag:'ARKEOLOGJI',title:'Akrolisi',text:'Akrolisi është një vendbanim i fortifikuar i hershëm në zonën e Malit të Shëlbuemit. Gjurmët e tij dhe pozicioni në reliev ndihmojnë në leximin e peizazhit arkeologjik të Lezhës.',source:'https://lezhaturistike.wordpress.com/vizito/'},skenderbeu:{tag:'MEMORIAL',title:'Vendvarrimi i Skënderbeut',text:'Vendvarrimi i Gjergj Kastriotit është një vend përkujtimor në Lezhë. Memoriali i sotëm u ndërtua në vitin 1981 mbi zonën e kishës së Shën Kollit.',source:'https://lezha.gov.al/resurset-turistike/'},kunevain:{tag:'NATYRË',title:'Kune–Vain–Tale',text:'Kompleksi ligatinor i Kune-Vainit është një destinacion për natyrën dhe vëzhgimin e shpendëve pranë Lezhës.',source:'https://lezhaturistike.wordpress.com/vizito/'}};
const dialog=document.getElementById('place-dialog');function showPlace(id,selected=0){const data=details[id],gallery=config.galleries?.[id];if(!data||!gallery)return;const photos=gallery.photos||[],photo=photos[selected]||photos[0];if(!photo)return;document.getElementById('dialog-image').src=photo.src;document.getElementById('dialog-image').alt=photo.alt||gallery.title;document.getElementById('dialog-tag').textContent=data.tag;document.getElementById('dialog-title').textContent=gallery.title||data.title;document.getElementById('dialog-text').textContent=data.text;document.getElementById('dialog-map').href='https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(data.title+', Lezhë, Albania');document.getElementById('dialog-source').href=data.source;const thumbnails=document.getElementById('dialog-gallery');thumbnails.replaceChildren();photos.forEach((item,index)=>{const button=document.createElement('button');button.type='button';button.className='gallery-thumb'+(index===selected?' selected':'');button.setAttribute('aria-label','Shfaq fotografinë '+(index+1)+': '+(item.alt||''));const img=document.createElement('img');img.src=item.src;img.alt='';button.append(img);button.addEventListener('click',()=>showPlace(id,index));thumbnails.append(button)});if(!dialog.open)dialog.showModal()}
document.querySelectorAll('.place-body a').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();showPlace(a.hash.slice(1))}));document.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});
const grid=document.getElementById('gallery-grid'),filterRow=document.getElementById('gallery-filters');let activeGallery='all';function renderGallery(){grid.replaceChildren();filterRow.replaceChildren();const names=Object.entries(config.galleries||{});[['all','Të gjitha'],...names.map(([id,g])=>[id,g.title])].forEach(([id,title])=>{const b=document.createElement('button');b.type='button';b.className='filter'+(activeGallery===id?' active':'');b.textContent=title;b.setAttribute('aria-pressed',String(activeGallery===id));b.addEventListener('click',()=>{activeGallery=id;renderGallery()});filterRow.append(b)});let count=0;names.forEach(([id,gallery])=>{if(activeGallery!=='all'&&activeGallery!==id)return;(gallery.photos||[]).forEach((photo,index)=>{const button=document.createElement('button');button.type='button';button.className='gallery-photo';button.setAttribute('aria-label','Hap fotografinë '+(photo.alt||gallery.title));const image=document.createElement('img');image.src=photo.src;image.alt=photo.alt||gallery.title;image.loading='lazy';const label=document.createElement('span');label.textContent=gallery.title;button.append(image,label);button.addEventListener('click',()=>showPlace(id,index));grid.append(button);count++})});if(!count){const p=document.createElement('p');p.className='gallery-empty';p.textContent='Nuk ka fotografi në këtë galeri.';grid.append(p)}}if(grid&&filterRow)renderGallery();
if(Array.isArray(config.extraSections)&&document.getElementById('kontakt')){const contact=document.getElementById('kontakt');config.extraSections.forEach((entry,index)=>{if(entry.visible===false||!entry.title)return;const id='seksion-'+index,section=document.createElement('section');section.className='section extra-section';section.id=id;const small=document.createElement('span');small.className='overline';small.textContent='LEZHA TURISTIKE';const h=document.createElement('h2');h.textContent=entry.title;const p=document.createElement('p');p.textContent=entry.text||'';section.append(small,h,p);if(entry.image){const image=document.createElement('img');image.src=entry.image;image.alt=entry.alt||entry.title;image.loading='lazy';section.append(image)}contact.before(section);const link=document.createElement('a');link.href='kontakt.html#'+id;link.textContent=entry.title;nav.insertBefore(link,nav.querySelector('a[href="kontakt.html"]'))})}

const backToTop=document.querySelector('.back-to-top');function updateBackToTop(){backToTop.classList.toggle('visible',window.scrollY>240)}window.addEventListener('scroll',updateBackToTop,{passive:true});updateBackToTop();

const gisFrame=document.getElementById('gis-iframe'),gisOriginal=document.getElementById('gis-original'),gisTitle=document.getElementById('gis-embed-title');
if(gisFrame){const gisTabs=[...document.querySelectorAll('.gis-tab')];
function loadGisFrame(){if(gisFrame.dataset.src){gisFrame.src=gisFrame.dataset.src;delete gisFrame.dataset.src}}
gisTabs.forEach(tab=>tab.addEventListener('click',()=>{
  gisTabs.forEach(item=>{const active=item===tab;item.classList.toggle('active',active);item.setAttribute('aria-pressed',String(active))});
  gisFrame.title=tab.dataset.gisTitle;gisTitle.textContent=tab.dataset.gisTitle;
  gisOriginal.href=tab.dataset.gisOriginal||tab.dataset.gisUrl;gisFrame.src=tab.dataset.gisUrl;delete gisFrame.dataset.src;
}));
if('IntersectionObserver' in window){const gisObserver=new IntersectionObserver(entries=>{if(entries[0].isIntersecting){loadGisFrame();gisObserver.disconnect()}},{rootMargin:'200px'});gisObserver.observe(gisFrame)}else loadGisFrame();

}