'use client'
import LocaleHeader from "@/app/components/LocaleHeader";
import SiteFooter from "@/app/components/SiteFooter";
import BackToTop from "@/app/components/BackToTop";
import { useEffect, useState } from 'react'

type Destinacion = {_id:string;titulli:string;kategoria:string;pershkrimi?:string;permbledhje?:string;cfareSheh?:string[];keshilleVizite?:string;kohezgjatja?:string;oraRekomanduar?:string;fotoUrl?:string;galeriaUrls?:string[];burimi?:string;burimiTitull?:string;harta?:string}
type Place = Destinacion & {tag:string;cardText:string;alt:string;big?:boolean;natureId?:boolean}
const categoryMeta:Record<string,{tag:string}>={histori:{tag:'TRASHËGIMI HISTORIKE'},arkeologji:{tag:'ARKEOLOGJI'},natyre:{tag:'NATYRË'}}

export default function DestinacioneClient({destinacionet}:{destinacionet:Destinacion[]}){
 const [filter,setFilter]=useState('all');const [selectedPlace,setSelectedPlace]=useState<Place|null>(null);const [selectedPhoto,setSelectedPhoto]=useState(0)
 const places:Place[]=destinacionet.map((item,index)=>{const meta=categoryMeta[item.kategoria]??{tag:'DESTINACION'};return{...item,tag:meta.tag,cardText:item.permbledhje||item.pershkrimi||'Zbulo këtë destinacion në Lezhë.',alt:item.titulli,big:index===0,natureId:item.kategoria==='natyre'}})
 const visiblePlaces=places.filter(place=>filter==='all'?true:filter==='natyre'?place.kategoria==='natyre':filter==='histori'?place.kategoria==='histori'||place.kategoria==='arkeologji':true)
 function openPlace(place:Place){setSelectedPlace(place);setSelectedPhoto(0)} function closePlace(){setSelectedPlace(null);setSelectedPhoto(0)}
 const gallery=selectedPlace?.galeriaUrls&&selectedPlace.galeriaUrls.length>0?selectedPlace.galeriaUrls:selectedPlace?.fotoUrl?[selectedPlace.fotoUrl]:[];const currentPhoto=gallery[selectedPhoto]||selectedPlace?.fotoUrl||''
 useEffect(()=>{if(!selectedPlace)return;const previous=document.activeElement as HTMLElement|null;const overflow=document.body.style.overflow;document.documentElement.classList.add('modal-open');document.body.classList.add('modal-open');const dialog=document.querySelector<HTMLElement>('[role="dialog"]');dialog?.querySelector<HTMLElement>('button')?.focus();const keydown=(event:KeyboardEvent)=>{if(event.key==='Escape')setSelectedPlace(null);if(event.key==='Tab'&&dialog){const items=Array.from(dialog.querySelectorAll<HTMLElement>('button, a[href], [tabindex="0"]'));const first=items[0],last=items[items.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus()}}};document.addEventListener('keydown',keydown);return()=>{document.documentElement.classList.remove('modal-open');document.body.classList.remove('modal-open');document.body.style.overflow=overflow;document.removeEventListener('keydown',keydown);previous?.focus()}},[selectedPlace])
 return <><LocaleHeader locale="sq" current="destinacione"/><main id="home"><section id="destinacione" className="section destinations"><div className="section-top"><div><span className="overline">EKSPLORO LEZHËN</span><h1>Vende për t’u zbuluar</h1></div><p>Njih historinë e qytetit përmes pikave të tij më të rëndësishme dhe peizazheve që e rrethojnë.</p></div><div className="filters" role="group" aria-label="Filtro destinacionet"><button className={`filter${filter==='all'?' active':''}`} type="button" onClick={()=>setFilter('all')}>Të gjitha</button><button className={`filter${filter==='histori'?' active':''}`} type="button" onClick={()=>setFilter('histori')}>Histori &amp; arkeologji</button><button className={`filter${filter==='natyre'?' active':''}`} type="button" onClick={()=>setFilter('natyre')}>Natyrë</button></div><div className="places">{visiblePlaces.map(place=><article key={place._id} className={`place${place.big?' big':''}`} data-category={place.kategoria} id={place.natureId?'natyre':undefined}><div className="place-image">{place.fotoUrl&&<img src={place.fotoUrl} alt={place.alt} loading="lazy"/>}</div><div className="place-body"><span className="tag">{place.tag}</span><h3>{place.titulli}</h3><p>{place.cardText}</p><a href="#" className="place-link" onClick={event=>{event.preventDefault();openPlace(place)}}>Zbulo vendin <span className="arrow-icon" aria-hidden="true">↗</span></a></div></article>)}</div></section></main><BackToTop locale="sq"/><SiteFooter locale="sq"/>
 {selectedPlace&&<div className="dialog-backdrop" role="presentation" onClick={closePlace}><div className="place-dialog" role="dialog" aria-modal="true" aria-labelledby="dialog-title" onClick={event=>event.stopPropagation()}><button type="button" className="dialog-close" aria-label="Mbyll" onClick={closePlace}>×</button>{currentPhoto&&<img src={currentPhoto} alt={selectedPlace.alt}/>}<div className="dialog-content"><span className="overline">{selectedPlace.tag}</span><h2 id="dialog-title">{selectedPlace.titulli}</h2><p>{selectedPlace.pershkrimi}</p>{(selectedPlace.kohezgjatja||selectedPlace.oraRekomanduar)&&<div className="visit-meta">{selectedPlace.kohezgjatja&&<span><b>Kohë e sugjeruar</b>{selectedPlace.kohezgjatja}</span>}{selectedPlace.oraRekomanduar&&<span><b>Momenti i rekomanduar</b>{selectedPlace.oraRekomanduar}</span>}</div>}{selectedPlace.cfareSheh&&selectedPlace.cfareSheh.length>0&&<div className="visit-highlights"><h3>Çfarë do të shohësh</h3><ul>{selectedPlace.cfareSheh.map(item=><li key={item}>{item}</li>)}</ul></div>}{selectedPlace.keshilleVizite&&<div className="visit-tip"><b>Këshillë për vizitën</b><p>{selectedPlace.keshilleVizite}</p></div>}{gallery.length>0&&<div className="dialog-gallery" aria-label="Galeria">{gallery.map((photo,index)=><button key={`${photo}-${index}`} type="button" className={`gallery-thumb${selectedPhoto===index?' selected':''}`} onClick={()=>setSelectedPhoto(index)} aria-label={`Foto ${index+1}`}><img src={photo} alt=""/></button>)}</div>}<div className="dialog-actions sq-dialog-actions">{selectedPlace.harta&&<a className="button dark" href={selectedPlace.harta} target="_blank" rel="noopener noreferrer"><span>Shiko vendndodhjen</span><span className="arrow-icon" aria-hidden="true">↗</span></a>}{selectedPlace.burimi&&<a className="button outline sq-info-link" href={selectedPlace.burimi} target="_blank" rel="noopener noreferrer"><span>{selectedPlace.burimiTitull||'Burimi institucional'}</span><span className="arrow-icon" aria-hidden="true">↗</span></a>}</div></div></div></div>}
 <style jsx>{`.visit-meta{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin:20px 0}.visit-meta span,.visit-tip{border:1px solid rgba(23,61,57,.14);border-radius:14px;padding:12px 14px}.visit-meta b,.visit-tip b{display:block;font-size:.7rem;text-transform:uppercase;letter-spacing:.08em;margin-bottom:5px}.visit-highlights{margin:20px 0}.visit-highlights h3{font-size:1rem;margin-bottom:8px}.visit-highlights ul{margin:0;padding-left:20px}.visit-highlights li{margin:6px 0}.visit-tip p{margin:4px 0 0}:global(html[data-theme="dark"]) .visit-meta span,:global(html[data-theme="dark"]) .visit-tip{border-color:rgba(247,243,236,.2)}@media (max-width:620px){.visit-meta{grid-template-columns:1fr}{.sq-dialog-actions{display:grid!important;grid-template-columns:1fr!important;gap:10px!important;width:100%!important;margin-top:26px}.sq-dialog-actions>a{box-sizing:border-box;width:100%!important;min-height:56px;margin:0!important;display:flex!important;align-items:center!important;justify-content:space-between!important;gap:16px;padding:15px 18px!important;font-size:.86rem;font-weight:700;text-decoration:none}.sq-dialog-actions .sq-info-link,.sq-dialog-actions .sq-info-link:link,.sq-dialog-actions .sq-info-link:visited,.sq-dialog-actions .sq-info-link:hover,.sq-dialog-actions .sq-info-link:active{border:1px solid #173d39!important;color:#173d39!important;-webkit-text-fill-color:#173d39!important;background:#fff!important;opacity:1!important}.sq-dialog-actions .sq-info-link span,.sq-dialog-actions .sq-info-link .arrow-icon{color:#173d39!important;-webkit-text-fill-color:#173d39!important;opacity:1!important;visibility:visible!important}.sq-dialog-actions .arrow-icon{flex:0 0 auto;margin-left:auto}}:global(html[data-theme="dark"]) .sq-dialog-actions .sq-info-link,:global(html[data-theme="dark"]) .sq-dialog-actions .sq-info-link:link,:global(html[data-theme="dark"]) .sq-dialog-actions .sq-info-link:visited,:global(html[data-theme="dark"]) .sq-dialog-actions .sq-info-link:hover,:global(html[data-theme="dark"]) .sq-dialog-actions .sq-info-link:active{color:#f7f3ec!important;-webkit-text-fill-color:#f7f3ec!important;opacity:1!important;border-color:rgba(247,243,236,.38)!important;background:transparent!important}:global(html[data-theme="dark"]) .sq-dialog-actions .sq-info-link span,:global(html[data-theme="dark"]) .sq-dialog-actions .sq-info-link .arrow-icon{color:#f7f3ec!important;-webkit-text-fill-color:#f7f3ec!important;opacity:1!important;visibility:visible!important}`}</style></>
}
