'use client'
import LocaleHeader from "@/app/components/LocaleHeader";
import SiteFooter from '@/app/components/SiteFooter'
import BackToTop from "@/app/components/BackToTop";
import { useEffect, useState } from 'react'

type Destinacion={_id:string;titulli:string;titulliEn?:string;kategoria:string;pershkrimi?:string;pershkrimiEn?:string;fotoUrl?:string;galeriaUrls?:string[];burimi?:string;harta?:string}
type Place=Destinacion&{tag:string;cardText:string;alt:string;big?:boolean;natureId?:boolean}
const categoryMeta:Record<string,{tag:string}>={histori:{tag:'HISTORICAL HERITAGE'},arkeologji:{tag:'ARCHAEOLOGY'},natyre:{tag:'NATURE'}}
export default function DestinacioneEnClient({destinacionet}:{destinacionet:Destinacion[]}){
 const [filter,setFilter]=useState('all');const [selectedPlace,setSelectedPlace]=useState<Place|null>(null);const [selectedPhoto,setSelectedPhoto]=useState(0)
 const places:Place[]=destinacionet.map((item,index)=>{const meta=categoryMeta[item.kategoria]??{tag:'DESTINATION'};return{...item,tag:meta.tag,cardText:item.pershkrimi||'Discover this destination in Lezhë.',alt:item.titulli,big:index===0,natureId:item.kategoria==='natyre'}})
 const visiblePlaces=places.filter(place=>filter==='all'?true:filter==='natyre'?place.kategoria==='natyre':filter==='histori'?place.kategoria==='histori'||place.kategoria==='arkeologji':true)
 function openPlace(place:Place){setSelectedPlace(place);setSelectedPhoto(0)} function closePlace(){setSelectedPlace(null);setSelectedPhoto(0)}
 const gallery=selectedPlace?.galeriaUrls&&selectedPlace.galeriaUrls.length>0?selectedPlace.galeriaUrls:selectedPlace?.fotoUrl?[selectedPlace.fotoUrl]:[];const currentPhoto=gallery[selectedPhoto]||selectedPlace?.fotoUrl||''
 useEffect(()=>{if(!selectedPlace)return;const previous=document.activeElement as HTMLElement|null;const overflow=document.body.style.overflow;document.body.style.overflow='hidden';const dialog=document.querySelector<HTMLElement>('[role="dialog"]');dialog?.querySelector<HTMLElement>('button')?.focus();const keydown=(event:KeyboardEvent)=>{if(event.key==='Escape')setSelectedPlace(null);if(event.key==='Tab'&&dialog){const items=Array.from(dialog.querySelectorAll<HTMLElement>('button, a[href], [tabindex="0"]'));const first=items[0],last=items[items.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus()}}};document.addEventListener('keydown',keydown);return()=>{document.body.style.overflow=overflow;document.removeEventListener('keydown',keydown);previous?.focus()}},[selectedPlace])
 return <><LocaleHeader locale="en" current="destinacione"/><main id="home"><section id="destinacione" className="section destinations"><div className="section-top"><div><span className="overline">EXPLORE LEZHË</span><h1>Places to discover</h1></div><p>Discover the city through its most important landmarks and the landscapes that surround it.</p></div><div className="filters" role="group" aria-label="Filter destinations"><button className={`filter${filter==='all'?' active':''}`} type="button" onClick={()=>setFilter('all')}>All</button><button className={`filter${filter==='histori'?' active':''}`} type="button" onClick={()=>setFilter('histori')}>History &amp; archaeology</button><button className={`filter${filter==='natyre'?' active':''}`} type="button" onClick={()=>setFilter('natyre')}>Nature</button></div><div className="places">{visiblePlaces.map(place=><article key={place._id} className={`place${place.big?' big':''}`} data-category={place.kategoria} id={place.natureId?'natyre':undefined}><div className="place-image">{place.fotoUrl&&<img src={place.fotoUrl} alt={place.alt} loading="lazy"/>}</div><div className="place-body"><span className="tag">{place.tag}</span><h3>{place.titulli}</h3><p>{place.cardText}</p><a href="#" className="place-link" onClick={event=>{event.preventDefault();openPlace(place)}}>Discover place <span className="arrow-icon" aria-hidden="true">↗</span></a></div></article>)}</div></section></main><BackToTop locale="en"/><SiteFooter locale="en"/>
 {selectedPlace&&<div className="dialog-backdrop" role="presentation" onClick={closePlace}><div className="place-dialog" role="dialog" aria-modal="true" aria-labelledby="dialog-title" onClick={event=>event.stopPropagation()}><button type="button" className="dialog-close" aria-label="Close" onClick={closePlace}>×</button>{currentPhoto&&<img src={currentPhoto} alt={selectedPlace.alt}/>}<div className="dialog-content"><span className="overline">{selectedPlace.tag}</span><h2 id="dialog-title">{selectedPlace.titulli}</h2><p>{selectedPlace.pershkrimi}</p>{gallery.length>0&&<div className="dialog-gallery" aria-label="Gallery">{gallery.map((photo,index)=><button key={`${photo}-${index}`} type="button" className={`gallery-thumb${selectedPhoto===index?' selected':''}`} onClick={()=>setSelectedPhoto(index)} aria-label={`Photo ${index+1}`}><img src={photo} alt=""/></button>)}</div>}<div className="dialog-actions">{selectedPlace.harta&&<a className="button dark" href={selectedPlace.harta} target="_blank" rel="noopener noreferrer">View location <span className="arrow-icon" aria-hidden="true">↗</span></a>}{selectedPlace.burimi&&<a href={selectedPlace.burimi} target="_blank" rel="noopener noreferrer">More information <span className="arrow-icon" aria-hidden="true">↗</span></a>}</div></div></div></div>}</>
}
