import {defineField,defineType} from 'sanity'
export const kulinari=defineType({name:'kulinari',title:'Kulinari',type:'document',fields:[
 defineField({name:'titulli',title:'Emri',type:'string',validation:(Rule)=>Rule.required()}),defineField({name:'kategoria',title:'Kategoria',type:'string',validation:(Rule)=>Rule.required(),options:{list:[{title:'Restorant',value:'restorant'},{title:'Agroturizëm',value:'agroturizem'},{title:'Kantinë',value:'kantine'},{title:'Bar / Kafe',value:'bar-kafe'},{title:'Produkte lokale',value:'produkte-lokale'},{title:'Tjetër',value:'tjeter'}]}}),
 defineField({name:'titulliEn',title:'Name (EN)',type:'string'}),defineField({name:'pershkrimi',title:'Përshkrimi',type:'text',rows:6}),defineField({name:'pershkrimiEn',title:'Description (EN)',type:'text',rows:6}),
 defineField({name:'foto',title:'Foto kryesore',type:'image',options:{hotspot:true}}),defineField({name:'galeria',title:'Galeria e fotove',type:'array',of:[{type:'image',options:{hotspot:true}}]}),
 defineField({name:'adresa',title:'Adresa',type:'string'}),defineField({name:'adresaEn',title:'Address (EN)',type:'string'}),defineField({name:'orari',title:'Orari',type:'string'}),defineField({name:'orariEn',title:'Opening hours (EN)',type:'string'}),
 defineField({name:'lokacioni',title:'Lokacioni për Planifiko vizitën',type:'geopoint',description:'Opsionale. Pa koordinata subjekti mund të publikohet normalisht; sapo vendoset pika, hyn automatikisht në Planifiko, hartë dhe routing.'}),defineField({name:'zona',title:'Zona / lokaliteti',type:'string',description:'P.sh. Lezhë, Shëngjin, Tale.'}),
 defineField({name:'searchKeywords',title:'Fjalë kyçe për kërkim',type:'array',of:[{type:'string'}],description:'P.sh. peshk, seafood, tradicionale, familje, darkë, kafe, agroturizëm.'}),
 defineField({name:'plannerTags',title:'Interesat në planner',type:'array',description:'Përdoren për kërkim dhe gjenerimin automatik të itinerareve.',of:[{type:'string'}],validation:(Rule)=>Rule.min(1).warning('Zgjidh të paktën një interes për sugjerime më të sakta në Planner.'),options:{list:[{title:'Kulinari',value:'Kulinari'},{title:'Natyrë & Bregdet',value:'Natyrë & Bregdet'},{title:'Eksplorim',value:'Eksplorim'},{title:'E kombinuar',value:'E kombinuar'}]}}),
 defineField({name:'telefoni',title:'Telefoni',type:'string'}),defineField({name:'harta',title:'Google Maps / Lokacioni',type:'url'}),defineField({name:'menuja',title:'Menuja (link)',type:'url'}),defineField({name:'website',title:'Website',type:'url'}),defineField({name:'social',title:'Instagram / Facebook',type:'url'}),defineField({name:'rezervimi',title:'Rezervimi (link)',type:'url'}),defineField({name:'burimi',title:'Burimi / Më shumë informacion',type:'url'}),
 defineField({name:'cmimiNga',title:'Çmimi nga',type:'number'}),defineField({name:'monedha',title:'Monedha',type:'string',options:{list:[{title:'€ EUR',value:'EUR'},{title:'$ USD',value:'USD'},{title:'Lek ALL',value:'ALL'}]}}),defineField({name:'cmimiPer',title:'Çmimi për',type:'string'}),
 defineField({name:'featured',title:'I veçuar',type:'boolean',initialValue:false}),defineField({name:'plannerThematicTours',title:'Turet tematike',type:'array',description:'Opsionale. Zgjidh turet tematike ku duhet të përfshihet kjo pikë. Lidhja ruhet me ID dhe nuk prishet nëse ndryshon titulli.',of:[{type:'string'}],options:{list:[{title:'Në Gjurmët e Lezhës',value:'gjurmet'},{title:'Lezha Antike',value:'antike'},{title:'Gjurmët e Skënderbeut',value:'skenderbeu'},{title:'Lezhë · Shëngjin · Rana',value:'bregdeti'},{title:'Kune–Vain · Tale',value:'lagunat'},{title:'Trashëgimia fetare',value:'trashegimia'}]}}),defineField({name:'plannerFeatured',title:'Sugjero te Planifiko vizitën',type:'boolean',description:'Opsionale. Aktivizoje për t’i dhënë përparësi subjektit në sugjerimet automatike.',initialValue:false}),defineField({name:'plannerOrder',title:'Renditja në itinerar',type:'number'}),defineField({name:'kohezgjatja',title:'Kohëzgjatja e rekomanduar',type:'string'}),defineField({name:'kohezgjatjaEn',title:'Recommended duration (EN)',type:'string'}),defineField({name:'plannerOpeningTime',title:'Hapet në',type:'string',description:'Opsionale. Ora e hapjes që përdor Planifiko, në formatin 24-orësh HH:MM, p.sh. 09:00.',validation:(Rule)=>Rule.regex(/^([01]\\d|2[0-3]):[0-5]\\d$/,{name:'ora HH:MM',invert:false}).warning('Përdor formatin HH:MM, p.sh. 09:00.')}),defineField({name:'plannerClosingTime',title:'Mbyllet në',type:'string',description:'Opsionale. Ora e mbylljes që përdor Planifiko, në formatin 24-orësh HH:MM, p.sh. 17:00.',validation:(Rule)=>Rule.regex(/^([01]\\d|2[0-3]):[0-5]\\d$/,{name:'ora HH:MM',invert:false}).warning('Përdor formatin HH:MM, p.sh. 17:00.')}),defineField({name:'momentiRekomanduar',title:'Koha e rekomanduar e vizitës',type:'string',description:'Përdoret nga Planifiko për ta vendosur ndalesën në pjesën më të përshtatshme të ditës.',options:{list:[{title:'Paradite',value:'morning'},{title:'Mesditë',value:'midday'},{title:'Pasdite',value:'afternoon'},{title:'Perëndim',value:'sunset'},{title:'Mbrëmje',value:'evening'},{title:'Çdo kohë',value:'anytime'}]},initialValue:'anytime'}),defineField({name:'oraRekomanduar',title:'Ora / momenti i rekomanduar (tekst)',type:'string',description:'Opsionale. Shënim i lirë për vizitorin, p.sh. 1–2 orë para perëndimit.'}),defineField({name:'oraRekomanduarEn',title:'Recommended time note (EN)',type:'string'})
],preview:{select:{title:'titulli',subtitle:'kategoria',media:'foto'}}})