import {defineField,defineType} from 'sanity'
export const kulinari=defineType({name:'kulinari',title:'Kulinari',type:'document',fields:[
 defineField({name:'titulli',title:'Emri',type:'string',validation:(Rule)=>Rule.required()}),defineField({name:'kategoria',title:'Kategoria',type:'string',options:{list:[{title:'Restorant',value:'restorant'},{title:'Agroturizëm',value:'agroturizem'},{title:'Kantinë',value:'kantine'},{title:'Bar / Kafe',value:'bar-kafe'},{title:'Produkte lokale',value:'produkte-lokale'},{title:'Tjetër',value:'tjeter'}]}}),
 defineField({name:'titulliEn',title:'Name (EN)',type:'string'}),defineField({name:'pershkrimi',title:'Përshkrimi',type:'text',rows:6}),defineField({name:'pershkrimiEn',title:'Description (EN)',type:'text',rows:6}),
 defineField({name:'foto',title:'Foto kryesore',type:'image',options:{hotspot:true}}),defineField({name:'galeria',title:'Galeria e fotove',type:'array',of:[{type:'image',options:{hotspot:true}}]}),
 defineField({name:'adresa',title:'Adresa',type:'string'}),defineField({name:'adresaEn',title:'Address (EN)',type:'string'}),defineField({name:'orari',title:'Orari',type:'string'}),defineField({name:'orariEn',title:'Opening hours (EN)',type:'string'}),
 defineField({name:'lokacioni',title:'Lokacioni për Planifiko vizitën',type:'geopoint',description:'Koordinatat përdoren për hartën dhe routing-un.'}),defineField({name:'zona',title:'Zona / lokaliteti',type:'string',description:'P.sh. Lezhë, Shëngjin, Tale.'}),
 defineField({name:'searchKeywords',title:'Fjalë kyçe për kërkim',type:'array',of:[{type:'string'}],description:'P.sh. peshk, seafood, tradicionale, familje, darkë, kafe, agroturizëm.'}),
 defineField({name:'plannerTags',title:'Interesat në planner',type:'array',of:[{type:'string'}],options:{list:[{title:'Kulinari',value:'Kulinari'},{title:'Natyrë & Bregdet',value:'Natyrë & Bregdet'},{title:'Eksplorim',value:'Eksplorim'},{title:'E kombinuar',value:'E kombinuar'}]}}),
 defineField({name:'telefoni',title:'Telefoni',type:'string'}),defineField({name:'harta',title:'Google Maps / Lokacioni',type:'url'}),defineField({name:'menuja',title:'Menuja (link)',type:'url'}),defineField({name:'website',title:'Website',type:'url'}),defineField({name:'social',title:'Instagram / Facebook',type:'url'}),defineField({name:'rezervimi',title:'Rezervimi (link)',type:'url'}),defineField({name:'burimi',title:'Burimi / Më shumë informacion',type:'url'}),
 defineField({name:'cmimiNga',title:'Çmimi nga',type:'number'}),defineField({name:'monedha',title:'Monedha',type:'string',options:{list:[{title:'€ EUR',value:'EUR'},{title:'$ USD',value:'USD'},{title:'Lek ALL',value:'ALL'}]}}),defineField({name:'cmimiPer',title:'Çmimi për',type:'string'}),
 defineField({name:'featured',title:'I veçuar',type:'boolean',initialValue:false}),defineField({name:'plannerFeatured',title:'Sugjero te Planifiko vizitën',type:'boolean',initialValue:false}),defineField({name:'plannerOrder',title:'Renditja në itinerar',type:'number'}),defineField({name:'kohezgjatja',title:'Kohëzgjatja e rekomanduar',type:'string'}),defineField({name:'oraRekomanduar',title:'Ora / momenti i rekomanduar',type:'string'})
],preview:{select:{title:'titulli',subtitle:'kategoria',media:'foto'}}})