'use client';
import {useMemo} from 'react';
export type MapPlace={name:string;lat:number;lng:number;note:string};
type Props={places:MapPlace[];active:number;onActive:(i:number)=>void;transport:string};
export default function LiveTourMap({places,active,onActive,transport}:Props){
 const current=places[Math.min(active,Math.max(places.length-1,0))];
 const mapUrl=useMemo(()=>current?`https://www.openstreetmap.org/export/embed.html?bbox=${current.lng-.045}%2C${current.lat-.03}%2C${current.lng+.045}%2C${current.lat+.03}&layer=mapnik&marker=${current.lat}%2C${current.lng}`:'',[current]);
 const mode=transport==='Në këmbë'?'walking':transport==='Biçikletë'?'bicycling':'driving';
 const directions=useMemo(()=>{if(places.length<2)return '';const origin=places[0],dest=places[places.length-1],wps=places.slice(1,-1).map(p=>`${p.lat},${p.lng}`).join('|');return `https://www.google.com/maps/dir/?api=1&origin=${origin.lat},${origin.lng}&destination=${dest.lat},${dest.lng}&waypoints=${encodeURIComponent(wps)}&travelmode=${mode}`},[places,mode]);
 if(!current)return null;
 return <div className="mapWrap"><div className="map"><iframe key={mapUrl} title={`Harta – ${current.name}`} src={mapUrl} loading="lazy"/><div className="badge"><small>NDALËSA {active+1}/{places.length}</small><b>{current.name}</b><span>{current.note}</span></div></div><div className="strip">{places.map((p,i)=><button key={p.name} className={i===active?'on':''} onClick={()=>onActive(i)} aria-label={`Shfaq ${p.name}`}><span>{i+1}</span><b>{p.name}</b></button>)}</div>{directions&&<a className="routeLink" href={directions} target="_blank" rel="noreferrer">Hap itinerarin e plotë · {transport}<span>↗</span></a>}<style jsx>{`.mapWrap{position:sticky;top:92px}.map{height:min(68vh,650px);min-height:560px;position:relative;border-radius:24px;overflow:hidden;border:1px solid rgba(23,61,57,.16);background:#e9ece7}.map iframe{width:100%;height:100%;border:0;display:block;filter:saturate(.82) contrast(.95)}.badge{position:absolute;left:18px;bottom:18px;max-width:330px;background:rgba(247,243,236,.94);color:#173d39;padding:15px 17px;border-radius:16px;box-shadow:0 12px 35px rgba(0,0,0,.12);backdrop-filter:blur(10px)}.badge small,.badge b,.badge span{display:block}.badge small{font-size:.61rem;letter-spacing:.1em;opacity:.55}.badge b{font-size:1.12rem;margin:4px 0}.badge span{font-size:.78rem;opacity:.65}.strip{display:flex;gap:6px;overflow-x:auto;padding:10px 1px 2px;scrollbar-width:none}.strip::-webkit-scrollbar{display:none}.strip button{flex:0 0 auto;border:1px solid rgba(23,61,57,.16);background:transparent;color:inherit;border-radius:999px;padding:8px 11px;display:flex;align-items:center;gap:7px;cursor:pointer}.strip button span{width:22px;height:22px;border-radius:50%;display:grid;place-items:center;border:1px solid rgba(23,61,57,.18);font-size:.65rem}.strip button b{font-size:.72rem}.strip button.on{background:#173d39;color:#f7f3ec}.routeLink{margin-top:10px;display:flex;justify-content:space-between;align-items:center;padding:15px 19px;border-radius:999px;background:#173d39;color:#f7f3ec;text-decoration:none;font-size:.82rem;font-weight:850}@media(max-width:900px){.mapWrap{position:relative;top:auto}.map{min-height:520px}}@media(max-width:620px){.map{min-height:430px;height:58vh}.badge{left:11px;right:11px;bottom:11px;max-width:none}.strip button b{max-width:110px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}}`}</style></div>
}