'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import LiveTourMap,{type MapPlace} from '../planifiko/LiveTourMap';

export type PlannerPlace={id:string;type:string;name:string;kind?:string;desc?:string;lat:number;lng:number;image?:string;duration?:string;plannerFeatured?:boolean;tags?:string[]};
const interests=['Histori & Arkeologji','Trashëgimi fetare','Kulturë urbane','Natyrë & Bregdet','Kulinari','Eksplorim','E kombinuar'];
const times=['3–4 orë','1 ditë','2 ditë','3 ditë'];
const transports=['Në këmbë','Makinë','Biçikletë'];
const thematic=[
 {id:'gjurmet',name:'Në Gjurmët e Lezhës',interest:'E kombinuar',names:['Memoriali i Skënderbeut','Kalaja e Lezhës','Rana e Hedhun','Lagunat Kune–Vain','Kune–Vain']},
 {id:'antike',name:'Lezha Antike',interest:'Histori & Arkeologji',names:['Qyteti antik i Lissusit','Kalaja e Lezhës','Memoriali i Skënderbeut','Obelisku i Kuvendit të Lezhës']},
 {id:'skenderbeu',name:'Gjurmët e Skënderbeut',interest:'Histori & Arkeologji',names:['Memoriali i Skënderbeut','Obelisku i Kuvendit të Lezhës','Kalaja e Lezhës']},
 {id:'bregdeti',name:'Lezhë · Shëngjin · Rana',interest:'Natyrë & Bregdet',names:['Shëngjini','Rana e Hedhun']},
 {id:'lagunat',name:'Kune–Vain · Tale',interest:'Natyrë & Bregdet',names:['Lagunat Kune–Vain','Kune–Vain','Plazhi i Tales']},
 {id:'trashegimia',name:'Trashëgimia fetare',interest:'Trashëgimi fetare',names:['Katedralja e qytetit','Kisha e Shën Eufemisë','Kisha e Kuvendit të Arbnit']}
];
const norm=(v:string)=>v.toLocaleLowerCase('sq').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/g,'');
const km=(a:PlannerPlace,b:PlannerPlace)=>{const r=6371,dLat=(b.lat-a.lat)*Math.PI/180,dLng=(b.lng-a.lng)*Math.PI/180,x=Math.sin(dLat/2)**2+Math.cos(a.lat*Math.PI/180)*Math.cos(b.lat*Math.PI/180)*Math.sin(dLng/2)**2;return 2*r*Math.asin(Math.sqrt(x))};
const optimize=(items:PlannerPlace[])=>{if(items.length<2)return items;const left=items.slice(1),out=[items[0]];while(left.length){const last=out.at(-1)!;left.sort((a,b)=>km(last,a)-km(last,b));out.push(left.shift()!)}return out};
const parseMin=(v='1 orë')=>{const h=v.match(/(\d+(?:[.,]\d+)?)\s*(?:h|or[ëe])/i),m=v.match(/(\d+)\s*min/i);return Math.max(30,Math.round(Number((h?.[1]||'0').replace(',','.'))*60+Number(m?.[1]||0)))};

export default function PlannerV2Client({cmsPlaces=[],locale='sq'}:{cmsPlaces:PlannerPlace[];locale?:'sq'|'en'}){
 const source=useMemo(()=>cmsPlaces.filter(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lng)&&p.lat!==0&&p.lng!==0),[cmsPlaces]);
 const[interest,setInterest]=useState('E kombinuar'),[time,setTime]=useState('1 ditë'),[transport,setTransport]=useState('Makinë');
 const[stops,setStops]=useState<PlannerPlace[]>([]),[active,setActive]=useState(0),[query,setQuery]=useState(''),[searchOpen,setSearchOpen]=useState(false),[qr,setQr]=useState(false),[mobileFloat,setMobileFloat]=useState<'themes'|'planner'|null>(null),[printFitSignal,setPrintFitSignal]=useState(0);
 const searchRef=useRef<HTMLDivElement|null>(null);
 useEffect(()=>{const close=(e:PointerEvent)=>{if(searchOpen&&searchRef.current&&!searchRef.current.contains(e.target as Node)){setSearchOpen(false);(document.activeElement as HTMLElement|null)?.blur?.()}};document.addEventListener('pointerdown',close);return()=>document.removeEventListener('pointerdown',close)},[searchOpen]);
 const en=locale==='en';
 const interestEN:Record<string,string>={'Histori & Arkeologji':'History & Archaeology','Trashëgimi fetare':'Religious heritage','Kulturë urbane':'Urban culture','Natyrë & Bregdet':'Nature & Coast','Kulinari':'Culinary','Eksplorim':'Exploration','E kombinuar':'Combined'};
 const timeEN:Record<string,string>={'3–4 orë':'3–4 hours','1 ditë':'1 day','2 ditë':'2 days','3 ditë':'3 days'};
 const transportEN:Record<string,string>={'Në këmbë':'Walking','Makinë':'Car','Biçikletë':'Bicycle'};
 const themeEN:Record<string,string>={gjurmet:'In the Footsteps of Lezha',antike:'Ancient Lezha',skenderbeu:"Skanderbeg's Footsteps",bregdeti:'Lezha · Shëngjin · Rana',lagunat:'Kune–Vain · Tale',trashegimia:'Religious Heritage'};
 const matches=useMemo(()=>{const q=norm(query);const list=q?source.filter(p=>norm([p.name,p.kind,p.desc,...(p.tags||[])].filter(Boolean).join(' ')).includes(q)):source;return list.slice(0,12)},[query,source]);
 const add=(p:PlannerPlace)=>{const scrollY=typeof window!=='undefined'?window.scrollY:0;const existing=stops.findIndex(x=>x.id===p.id);if(existing>=0)setActive(existing);else{const next=optimize([...stops,p]);setStops(next);setActive(next.findIndex(x=>x.id===p.id))}setQuery('');setSearchOpen(false);(document.activeElement as HTMLElement|null)?.blur?.();if(typeof window!=='undefined'){requestAnimationFrame(()=>window.scrollTo({top:scrollY,left:0,behavior:'auto'}));setTimeout(()=>window.scrollTo({top:scrollY,left:0,behavior:'auto'}),120)}};
 const generate=()=>{const keys:Record<string,string[]>={
  'Histori & Arkeologji':['histori','arkeolog','kala','lissus','memorial','skenderbe'],
  'Trashëgimi fetare':['kish','katedrale','fetar','kuvendit te arbnit'],
  'Kulturë urbane':['kultur','qytet','urban','obelisk','memorial'],
  'Natyrë & Bregdet':['natyr','lagun','park','mal','kune','vain','bregdet','plazh','det','shengjin','tale','rana'],
  'Kulinari':['kulinari','restorant','ushqim','gatim'],
  'Eksplorim':['eksplor','ecje','mal','natyr','aventur']
 };let pool=interest==='E kombinuar'?source:source.filter(p=>{const s=norm([p.name,p.kind,...(p.tags||[])].join(' '));return (keys[interest]||[]).some(k=>s.includes(norm(k)))});if(pool.length<2)pool=source;pool=[...pool].sort((a,b)=>Number(b.plannerFeatured)-Number(a.plannerFeatured));const budget=time==='3–4 orë'?210:time==='1 ditë'?480:time==='2 ditë'?960:1440;let used=0;const picked:PlannerPlace[]=[];for(const p of pool){const visit=parseMin(p.duration),move=picked.length?30:0;if(used+visit+move>budget&&picked.length>=2)continue;picked.push(p);used+=visit+move;if(used>=budget*.82||picked.length>=8)break}setStops(optimize(picked));setActive(0);setMobileFloat(null)};
 const loadTheme=(t:(typeof thematic)[number])=>{const wanted=new Map(t.names.map((n,i)=>[norm(n),i]));let picked=source.filter(p=>wanted.has(norm(p.name))).sort((a,b)=>(wanted.get(norm(a.name))??99)-(wanted.get(norm(b.name))??99));if(!picked.length){const keys=t.interest==='Natyrë & Bregdet'?['plazh','lagun','bregdet','rana','tale']:t.interest==='Trashëgimi fetare'?['kish','katedrale','fetar']:['histori','arkeolog','kala','memorial'];picked=source.filter(p=>keys.some(k=>norm([p.name,p.kind,...(p.tags||[])].join(' ')).includes(norm(k)))).slice(0,6)}setInterest(t.interest);setStops(optimize(picked));setActive(0);setMobileFloat(null)};
 const mapPlaces:MapPlace[]=stops.map(p=>({name:p.name,lat:p.lat,lng:p.lng,note:p.kind||'Destinacion',description:p.desc,image:p.image}));
 const distance=stops.slice(1).reduce((n,p,i)=>n+km(stops[i],p),0),speed=transport==='Në këmbë'?4.5:transport==='Biçikletë'?15:38,travelMinutes=Math.round(distance/speed*60),visitMinutes=stops.reduce((n,p)=>n+parseMin(p.duration),0),totalMinutes=travelMinutes+visitMinutes;
 const fmtDuration=(mins:number)=>{if(!mins)return'—';const h=Math.floor(mins/60),m=mins%60;if(en)return h?`~${h} h${m?` ${m} min`:''}`:`~${m} min`;return h?`~${h} orë${m?` ${m} min`:''}`:`~${m} min`};
 const shareUrl=()=>{if(typeof window==='undefined')return'';const u=new URL(window.location.href);u.searchParams.set('koha',time);u.searchParams.set('interesi',interest);u.searchParams.set('transporti',transport);if(stops.length)u.searchParams.set('ndalesat',stops.map(s=>s.id).join(','));return u.toString()};
 const share=async()=>{const u=shareUrl();try{if(navigator.share)await navigator.share({title:en?'My itinerary in Lezha':'Itinerari im në Lezhë',url:u});else await navigator.clipboard.writeText(u)}catch{}};
 const googleMapsUrl=stops.length?`https://www.google.com/maps/dir/?api=1&origin=${stops[0].lat},${stops[0].lng}&destination=${stops.at(-1)!.lat},${stops.at(-1)!.lng}&waypoints=${stops.slice(1,-1).map(p=>`${p.lat},${p.lng}`).join('|')}&travelmode=${transport==='Në këmbë'?'walking':transport==='Biçikletë'?'bicycling':'driving'}`:'https://www.google.com/maps';
 const actionLabels=en?{share:'Share',shareSub:'Send itinerary',qr:'QR Code',qrSub:'Open on phone',map:'Open map',mapSub:'Full navigation'}:{share:'Ndaje',shareSub:'Dërgo itinerarin',qr:'QR Code',qrSub:'Hape në telefon',map:'Hap hartën',mapSub:'Navigim i plotë'};
 const qrUrl=`https://quickchart.io/qr?size=280&margin=2&text=${encodeURIComponent(shareUrl())}`;
 const printMap=()=>{if(!stops.length||typeof window==='undefined')return;setMobileFloat(null);setSearchOpen(false);document.body.classList.add('plannerV2Printing');setPrintFitSignal(v=>v+1);setTimeout(()=>{window.dispatchEvent(new Event('resize'));setPrintFitSignal(v=>v+1)},250);setTimeout(()=>window.print(),900);setTimeout(()=>document.body.classList.remove('plannerV2Printing'),2500)};
 return <div className="plannerV2"><div className="printTitle"><b>{en?'MY ITINERARY IN LEZHA':'ITINERARI IM NË LEZHË'}</b><span>{stops.length} {en?'stops':'ndalesa'} · {en?(transportEN[transport]||transport):transport}</span></div><section className="plannerStage">
  <div className="mapCanvas"><LiveTourMap places={mapPlaces} active={Math.min(active,Math.max(0,mapPlaces.length-1))} onActive={setActive} transport={transport} locale={locale} fitAllSignal={printFitSignal}/></div>

  <div className="searchFloat" ref={searchRef}>
   <label><span>⌕</span><input value={query} onFocus={()=>{setSearchOpen(true);setMobileFloat(null)}} onChange={e=>{setQuery(e.target.value);setSearchOpen(true);setMobileFloat(null)}} placeholder={en?"Search destinations, restaurants and accommodation...":"Kërko destinacione, restorante dhe akomodim..."}/>{query&&<button onClick={()=>{setQuery('');setSearchOpen(false);(document.activeElement as HTMLElement|null)?.blur?.()}}>×</button>}</label>
   {searchOpen&&<div className="searchResults">{matches.length?matches.map(p=><button key={p.id} type="button" onPointerDown={e=>e.preventDefault()} onClick={()=>add(p)}>{p.image?<img src={p.image} alt=""/>:<i>◎</i>}<span><b>{p.name}</b><small>{p.kind||(en?'Destination':'Destinacion')} · {p.type==='kulinari'?(en?'Culinary':'Kulinari'):p.type==='akomodim'?(en?'Accommodation':'Akomodim'):(en?'Destination':'Destinacion')}</small></span><em>{stops.some(s=>s.id===p.id)?(en?'In tour':'Në tur'):(en?'＋ Add':'＋ Shto')}</em></button>):<p>{en?'No results found.':'Nuk u gjet rezultat.'}</p>}</div>}
  </div>

  <button className="mobileFloatToggle themesToggle" onClick={()=>{setMobileFloat(mobileFloat==='themes'?null:'themes');setSearchOpen(false)}}>{en?'Thematic tours':'Ture tematike'} <span>⌄</span></button><div className={'thematicCard '+(mobileFloat==='themes'?'mobileOpen':'')}><small>{en?'THEMATIC TOURS':'TURE TEMATIKE'}</small><h3>{en?'Ready-made itineraries':'Itinerare të gatshme'}</h3><div>{thematic.map(t=><button key={t.id} onClick={()=>loadTheme(t)}><span><b>{en?(themeEN[t.id]||t.name):t.name}</b><small>{en?'Open itinerary':'Hap itinerarin'}</small></span><em>→</em></button>)}</div></div>

  <button className="mobileFloatToggle plannerToggle" onClick={()=>{setMobileFloat(mobileFloat==='planner'?null:'planner');setSearchOpen(false)}}>{en?'Plan your visit':'Planifiko vizitën'} <span>⌄</span></button><div className={'plannerPanel '+(mobileFloat==='planner'?'mobileOpen':'')}>
   <div className="panelHead"><span className="pin mapLogo" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="m3 6 5-2 8 3 5-2v13l-5 2-8-3-5 2Z"/><path d="M8 4v13M16 7v13"/></svg></span><div><small>{en?'YOUR DIGITAL GUIDE':'GUIDA JOTE DIGJITALE'}</small><h1>{en?'Plan your visit':'Planifiko vizitën'}</h1></div></div>
   <div className="step"><span className="stepNo">1</span><div><b>{en?'Choose interests':'Zgjidh interesat'}</b><div className="pills">{interests.map(x=><button key={x} className={interest===x?'selected':''} onClick={()=>setInterest(x)}>{en?(interestEN[x]||x):x}</button>)}</div></div></div>
   <div className="step"><span className="stepNo">2</span><div><b>{en?'Available time':'Koha në dispozicion'}</b><div className="pills">{times.map(x=><button key={x} className={time===x?'selected':''} onClick={()=>setTime(x)}>{en?(timeEN[x]||x):x}</button>)}</div></div></div>
   <div className="step"><span className="stepNo">3</span><div><b>{en?'Getting around':'Mënyra e lëvizjes'}</b><div className="transport">{transports.map(x=><button key={x} className={transport===x?'selected':''} onClick={()=>setTransport(x)}><span>{x==='Makinë'?'🚗':x==='Në këmbë'?'🚶':'🚲'}</span>{en?(transportEN[x]||x):x}</button>)}</div></div></div>
   <div className="plannerButtons"><button className="generateV2" onClick={generate}>{en?'Generate itinerary':'Gjenero itinerarin'} <span>→</span></button><div className="plannerMiniActions"><button onClick={()=>setSearchOpen(true)}>＋ {en?'Add':'Shto'}</button><button onClick={()=>{setStops([]);setActive(0)}} disabled={!stops.length}>{en?'Clear itinerary':'Pastro itinerarin'}</button></div></div>
  </div>

  <div className="leftBottomCluster"><div className="summaryCard"><small>{en?'SUGGESTED ITINERARY':'ITINERARI I SUGJERUAR'}</small><div><span>⌖</span><b>{stops.length||'—'} {en?'stops':'ndalesa'}</b></div><div><span>↝</span><b>{stops.length?distance.toFixed(1):'—'} km</b></div><div><span>◷</span><b>{stops.length?fmtDuration(totalMinutes):'—'}</b></div>{stops.length>0&&<small className="timeBreakdown">{en?'Travel':'Lëvizje'}: {fmtDuration(travelMinutes)} · {en?'Visits':'Vizita'}: {fmtDuration(visitMinutes)}</small>}</div>{stops.length>0&&<div className="selectedCards">{stops.map((p,i)=><button key={p.id} className={active===i?'active':''} onClick={()=>setActive(i)}>{p.image?<img src={p.image} alt=""/>:<span className="noPhoto">◎</span>}<span className="selectedText"><small>{en?'DESTINATION':'DESTINACIONI'} {i+1}</small><b>{p.name}</b><em>{p.desc||p.kind||'Ndalesë në itinerarin tënd.'}</em></span>{i<stops.length-1&&<strong className="nextArrow">→</strong>}</button>)}</div>}</div>
 </section>

 {stops.length>0&&<div className="mapActions"><button onClick={share} className="takeAction"><span className="actionIcon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.9" strokeLinecap="round" strokeLinejoin="round"><path d="M19 4 8 12l11 8V4Z"/></svg></span><b>{actionLabels.share}</b><small>{actionLabels.shareSub}</small></button><button onClick={()=>setQr(true)} className="takeAction"><span className="actionIcon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="3" width="6" height="6" rx=".5"/><rect x="15" y="3" width="6" height="6" rx=".5"/><rect x="3" y="15" width="6" height="6" rx=".5"/><path d="M15 15h3v3h3M21 15v3M15 21h3"/></svg></span><b>{actionLabels.qr}</b><small>{actionLabels.qrSub}</small></button><a href={googleMapsUrl} target="_blank" rel="noreferrer" className="takeAction"><span className="actionIcon mapActionIcon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="m3 6 5-2 8 3 5-2v13l-5 2-8-3-5 2Z"/><path d="M8 4v13M16 7v13"/></svg></span><b>{actionLabels.map}</b><small>{actionLabels.mapSub}</small></a></div>}
 {qr&&<div className="qrModal" onClick={()=>setQr(false)}><div onClick={e=>e.stopPropagation()}><button className="qrClose" onClick={()=>setQr(false)}>×</button><small>{en?'MY TOUR / QR':'TURI IM / QR'}</small><h3>{en?'Scan and continue on your phone':'Skano dhe vazhdo në telefon'}</h3><img src={qrUrl} alt="QR Code"/><p>{time} · {interest}<br/>{stops.length} {en?'stops':'ndalesa'} · {en?(transportEN[transport]||transport):transport}</p></div></div>}
 </div>
}