import {pageMetadata} from "@/app/seo";
export const metadata = pageMetadata("kontakt", "sq");
import SiteFooter from "@/app/components/SiteFooter";
import LocaleHeader from "@/app/components/LocaleHeader";
import BackToTop from "@/app/components/BackToTop";
import ContactForm from "./ContactForm";
import Link from "next/link";

export default function KontaktPage() {
  return <><LocaleHeader locale="sq" current="kontakt"/><main id="home">
    <section className="contact-hero section">
      <div className="contact-intro"><span className="overline">KONTAKT</span><h1>Planifiko vizitën<br/>tënde në Lezhë.</h1><p>Ke pyetje rreth destinacioneve, trashëgimisë kulturore, Web GIS apo projektit? Na shkruaj — formulari dërgon mesazhin direkt te Lezha Turistike.</p>
        <div className="contact-location"><span>LEZHË · SHQIPËRI</span><p>Një pikënisje për të zbuluar historinë, kulturën, natyrën dhe eksperiencat e Lezhës.</p></div>
        <div className="contact-quick-actions"><a className="write-button" href="#contact-form">Na shkruaj <span aria-hidden="true">↓</span></a><a className="contact-map-link" href="https://www.google.com/maps/search/?api=1&query=Lezhe%2C%20Albania" target="_blank" rel="noopener noreferrer">Shiko në hartë <span aria-hidden="true">↗</span></a></div>
      </div><ContactForm locale="sq"/>
    </section>
    <section className="contact-explore section"><div><span className="overline">VAZHDO EKSPLORIMIN</span><h2>Zbulo më shumë nga Lezha.</h2></div><nav aria-label="Eksploro Lezhën"><Link href="/destinacione"><span>01</span> Destinacione <span>↗</span></Link><Link href="/webgis"><span>02</span> Web GIS <span>↗</span></Link><Link href="/galeri"><span>03</span> Galeri <span>↗</span></Link></nav></section>
  </main><BackToTop/><SiteFooter locale="sq"/><style>{`
    html{scroll-behavior:smooth}.contact-hero{display:grid;grid-template-columns:minmax(0,.88fr) minmax(420px,1.12fr);gap:clamp(42px,7vw,100px);align-items:start;padding-top:clamp(70px,10vw,130px);padding-bottom:clamp(70px,10vw,120px)}.contact-intro{position:sticky;top:110px}.contact-intro h1{font-size:clamp(3rem,6vw,6.5rem);line-height:.92;letter-spacing:-.055em;margin:18px 0 28px;max-width:780px}.contact-intro>p{max-width:610px;font-size:1.05rem;line-height:1.75;opacity:.76}.contact-location{margin:40px 0 30px;padding:24px;border:1px solid rgba(23,61,57,.13);border-radius:18px;background:rgba(255,255,255,.35);max-width:560px}.contact-location span{font-size:.68rem;font-weight:800;letter-spacing:.15em;color:#b6763e}.contact-location p{margin:10px 0 0;line-height:1.55;opacity:.72}.contact-quick-actions{display:flex;align-items:center;gap:24px;flex-wrap:wrap}.write-button{min-width:190px;background:#173d39;color:#fff;text-decoration:none;padding:18px 20px;border-radius:12px;display:flex;justify-content:space-between;gap:30px;font-weight:800;transition:transform .2s}.write-button:hover{transform:translateY(-2px)}.contact-map-link{font-weight:800;color:inherit;text-decoration:none;border-bottom:1px solid currentColor;padding-bottom:5px}.contact-explore{padding-top:30px;padding-bottom:100px;display:grid;grid-template-columns:.8fr 1.2fr;gap:60px}.contact-explore h2{font-size:clamp(2rem,4vw,4rem);line-height:1;margin:14px 0}.contact-explore nav{border-top:1px solid rgba(23,61,57,.18)}.contact-explore nav a{display:grid;grid-template-columns:42px 1fr auto;align-items:center;gap:16px;padding:22px 4px;border-bottom:1px solid rgba(23,61,57,.18);color:inherit;text-decoration:none;font-size:1.15rem;font-weight:800}.contact-explore nav a>span:first-child{font-size:.68rem;opacity:.55}html[data-theme="dark"] .contact-location{background:rgba(255,255,255,.025);border-color:rgba(247,243,236,.14)}html[data-theme="dark"] .write-button{background:#f1e8da;color:#173d39}html[data-theme="dark"] .contact-explore nav,html[data-theme="dark"] .contact-explore nav a{border-color:rgba(247,243,236,.16)}@media(max-width:900px){.contact-hero{grid-template-columns:1fr}.contact-intro{position:static}.contact-explore{grid-template-columns:1fr;gap:28px}}@media(max-width:620px){.contact-hero{padding-top:52px;gap:38px}.contact-intro h1{font-size:clamp(2.8rem,14vw,4.4rem)}.contact-location{margin-top:30px}.contact-quick-actions{align-items:stretch;flex-direction:column}.write-button{min-width:0}.contact-map-link{width:max-content}.contact-explore{padding-bottom:70px}.contact-explore nav a{padding:19px 2px}}
  `}</style></>;
}
