"use client";
import LocaleHeader from "@/app/components/LocaleHeader";

import {useState} from "react";

import BackToTop from "@/app/components/BackToTop";
import SiteFooter from "@/app/components/SiteFooter";

type Item={_id:string;titulli:string;kategoria?:string;pershkrimi?:string;fotoUrl?:string;galeriaUrls?:string[];adresa?:string;orari?:string;telefoni?:string;harta?:string;menuja?:string;website?:string;social?:string;rezervimi?:string;burimi?:string;rating?:number;reviewCount?:number;cmimiNga?:number;monedha?:string;cmimiPer?:string;featured?:boolean};
const currency:Record<string,string>={EUR:"€",USD:"$",ALL:"Lek"};const per:Record<string,string>={person:"person",night:"natë",room:"dhomë",meal:"vakt"};const labels:Record<string,string>={restorant:"RESTORANT",agroturizem:"AGROTURIZËM",kantine:"KANTINË","bar-kafe":"BAR / KAFE","produkte-lokale":"PRODUKTE LOKALE",tjeter:"KULINARI"};

export default function KulinariClient({kulinari}:{kulinari:Item[]}){
 const [items,setItems]=useState(kulinari); const [selected,setSelected]=useState<Item|null>(null); const [photo,setPhoto]=useState(0);
 const vote=async(x:Item,n:number)=>{if(localStorage.getItem('rated-'+x._id))return alert('E ke vlerësuar tashmë këtë vend.');const res=await fetch('/api/reviews',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({placeId:x._id,rating:n})});const d=await res.json();if(!res.ok)return alert(d.error||'Vlerësimi nuk u ruajt.');localStorage.setItem('rated-'+x._id,String(n));setItems(v=>v.map(i=>i._id===x._id?{...i,rating:d.rating,reviewCount:d.reviewCount}:i));};
 const gallery=selected?.galeriaUrls?.length?selected.galeriaUrls:selected?.fotoUrl?[selected.fotoUrl]:[];
 const open=(x:Item)=>{setSelected(x);setPhoto(0);document.body.style.overflow="hidden"};
 const close=()=>{setSelected(null);document.body.style.overflow=""};
 return <><LocaleHeader locale="sq" current="kulinari" />
 <main id="home"><section id="kulinari" className="section destinations"><div className="section-top"><div><span className="overline">KULINARI</span><h1>Lezha shijohet edhe në tryezë.</h1></div><p>Zbulo restorante, agroturizme, kantina dhe produkte vendase.</p></div><div className="places">{items.map((x,i)=><article key={x._id} className={`place${x.featured||i===0?" big":""}`}><div className="place-image">{x.fotoUrl&&<img src={x.fotoUrl} alt={x.titulli} loading="lazy"/>}</div><div className="place-body"><span className="tag">{labels[x.kategoria||""]||"KULINARI"}</span><h3>{x.titulli}</h3><div className="culinary-rating-price"><div className="visitor-review"><div className="visitor-stars">{[1,2,3,4,5].map(n=><button key={n} type="button" onClick={()=>vote(x,n)} aria-label={`${n} yje`} className={n<=Math.round(x.rating||0)?"active":""}>★</button>)}</div><small>{x.reviewCount?`${(x.rating||0).toFixed(1)} · ${x.reviewCount} reviews`:"Jep vlerësimin"}</small></div>{x.cmimiNga!=null&&<span className="culinary-price"><small>nga</small><b>{currency[x.monedha||"EUR"]||x.monedha||"€"}{x.cmimiNga}</b>{x.cmimiPer&&<small>/ {per[x.cmimiPer]||x.cmimiPer}</small>}</span>}</div><p>{x.pershkrimi}</p>{(x.adresa||x.orari||x.telefoni)&&<div className="culinary-card-meta">{x.adresa&&<span className="culinary-meta-row"><i className="culinary-meta-icon pin" aria-hidden="true"/><em>{x.adresa}</em></span>}{x.orari&&<span className="culinary-meta-row"><i className="culinary-meta-icon clock" aria-hidden="true"/><em>{x.orari}</em></span>}{x.telefoni&&<a className="culinary-meta-row" href={`tel:${x.telefoni}`}><i className="culinary-meta-icon phone" aria-hidden="true"/><em>{x.telefoni}</em></a>}</div>}<button className="place-link-button" type="button" onClick={()=>open(x)}>Shiko vendin <span className="arrow-icon" aria-hidden="true">↗</span></button></div></article>)}</div></section></main>
 <BackToTop/>
 <SiteFooter/>
 {selected&&<div className="dialog-backdrop" onClick={close}><div className="place-dialog" role="dialog" aria-modal="true" onClick={e=>e.stopPropagation()}><button className="dialog-close" onClick={close} aria-label="Mbyll">×</button>{gallery[photo]&&<img src={gallery[photo]} alt={selected.titulli}/>}<div className="dialog-content"><span className="overline">{labels[selected.kategoria||""]||"KULINARI"}</span><h2>{selected.titulli}</h2><p>{selected.pershkrimi}</p><div className="culinary-details">{selected.adresa&&<div><b>Adresa</b><span>{selected.adresa}</span></div>}{selected.orari&&<div><b>Orari</b><span>{selected.orari}</span></div>}{selected.telefoni&&<div><b>Telefon</b><a href={`tel:${selected.telefoni}`}>{selected.telefoni}</a></div>}</div>{gallery.length>1&&<div className="dialog-gallery">{gallery.map((p,i)=><button key={p+i} className={`gallery-thumb${photo===i?" selected":""}`} onClick={()=>setPhoto(i)}><img src={p} alt=""/></button>)}</div>}<div className="culinary-actions">{selected.harta&&<a className="button dark" href={selected.harta} target="_blank" rel="noopener noreferrer">Google Maps <span className="arrow-icon" aria-hidden="true">↗</span></a>}{selected.menuja&&<a className="button outline" href={selected.menuja} target="_blank" rel="noopener noreferrer">Shiko menunë <span className="arrow-icon" aria-hidden="true">↗</span></a>}{selected.rezervimi&&<a className="button primary" href={selected.rezervimi} target="_blank" rel="noopener noreferrer">Rezervo <span className="arrow-icon" aria-hidden="true">↗</span></a>}{selected.website&&<a href={selected.website} target="_blank" rel="noopener noreferrer">Website <span className="arrow-icon" aria-hidden="true">↗</span></a>}{selected.social&&<a href={selected.social} target="_blank" rel="noopener noreferrer">Rrjetet sociale <span className="arrow-icon" aria-hidden="true">↗</span></a>}{selected.burimi&&<a href={selected.burimi} target="_blank" rel="noopener noreferrer">Më shumë informacion <span className="arrow-icon" aria-hidden="true">↗</span></a>}</div></div></div></div>}</>
}