import LocaleHeader from "@/app/components/LocaleHeader";
import SiteFooter from "@/app/components/SiteFooter";
import BackToTop from "@/app/components/BackToTop";
import Link from "next/link";

type Locale="sq"|"en"; type Kind="privacy"|"terms"|"cookies";
const copy={
sq:{
privacy:{eyebrow:"PRIVATËSIA",title:"Politika e Privatësisë",intro:"Kjo politikë shpjegon si Lezha Turistike trajton informacionin gjatë përdorimit të faqes.",sections:[
["Të dhënat dhe qëllimi","Faqja nuk kërkon krijimin e një llogarie nga vizitorët. Kur na kontaktoni me email, informacioni që dërgoni përdoret për t’ju përgjigjur dhe për komunikimin që keni kërkuar. Infrastrukturat e hosting-ut dhe shërbimet teknike mund të përpunojnë të dhëna teknike, si adresa IP, koha e kërkesës, pajisja ose të dhëna të ngjashme, për siguri dhe funksionim."],
["Preferencat dhe vlerësimet","Day/Night Mode ruan lokalisht në shfletues preferencën e temës. Te Kulinaria, shfletuesi ruan lokalisht faktin që një vend është vlerësuar, ndërsa vlerësimi 1–5 dërgohet në sistemin e faqes dhe ruhet në Sanity për llogaritjen e rezultatit të përgjithshëm. Ky funksion nuk kërkon emër apo email."],
["Shërbime të jashtme","Faqja përmban ose lidh shërbime të palëve të treta, përfshirë ArcGIS/Web GIS dhe lidhje drejt faqeve, hartave, rrjeteve sociale ose burimeve shkencore. Kur hapni ose ndërveproni me këto shërbime, ofruesi përkatës mund të përpunojë të dhëna sipas politikave të veta."],
["Ruajtja dhe siguria","Synojmë të kufizojmë të dhënat në atë që nevojitet për funksionimin, sigurinë, komunikimin dhe funksionet që kërkon vizitori. Të dhënat mbahen vetëm për aq kohë sa nevojiten për qëllimin përkatës ose sa kërkohet nga detyrimet ligjore."],
["Të drejtat tuaja","Në varësi të legjislacionit të zbatueshëm, mund të kërkoni informacion, akses, korrigjim ose fshirje të të dhënave personale që kontrollohen nga ne, si dhe të kundërshtoni ose kufizoni përpunimin kur këto të drejta zbatohen."],
["Kontakti","Për pyetje mbi privatësinë ose për ushtrimin e të drejtave, kontaktoni: lezhaturistike@gmail.com. Identiteti formal i operatorit/përgjegjësit të faqes do të plotësohet sapo të përcaktohet zyrtarisht."]]},
terms:{eyebrow:"KUSHTET",title:"Kushtet e Përdorimit",intro:"Duke përdorur Lezha Turistike, pranoni këto kushte bazë të përdorimit të përmbajtjes dhe shërbimeve të faqes.",sections:[
["Qëllimi i faqes","Lezha Turistike ofron informacion turistik, kulturor, historik, arkeologjik, shkencor dhe hartografik për qëllime informimi dhe promovimi."],
["Saktësia e informacionit","Përpiqemi ta mbajmë informacionin të saktë dhe të përditësuar, por oraret, çmimet, kontaktet, kushtet e hyrjes, vendndodhjet dhe informacionet e subjekteve të treta mund të ndryshojnë. Për vendime udhëtimi ose rezervime, verifikoni informacionin te ofruesi përkatës."],
["Hartat dhe Web GIS","Hartat, koordinatat, aplikacionet Web GIS dhe vizualizimet kanë karakter informues dhe nuk zëvendësojnë dokumentacionin zyrtar, kadastral, ligjor, navigimin profesional ose udhëzimet e autoriteteve."],
["Pronësia intelektuale","Tekstet, dizajni, fotografitë, hartat, të dhënat dhe materialet mund të mbrohen nga të drejta autori ose licenca të autorëve, institucioneve dhe partnerëve përkatës. Materialet e palëve të treta mbeten pronë e mbajtësve të tyre të të drejtave."],
["Lidhjet e jashtme","Faqja mund të lidhet me ArcGIS, Google Maps, faqe institucionale, rrjete sociale dhe burime të tjera. Lezha Turistike nuk kontrollon përmbajtjen, disponueshmërinë apo politikat e këtyre shërbimeve."],
["Përdorimi i pranueshëm","Mos përdorni faqen për ndërhyrje teknike, abuzim me funksionet, përpjekje për akses të paautorizuar ose përdorim që cenon të drejtat e të tjerëve."],
["Ndryshimet","Këto kushte mund të përditësohen kur ndryshojnë funksionet, përmbajtja ose kërkesat ligjore. Versioni i publikuar në këtë faqe është versioni aktual."]]},
cookies:{eyebrow:"COOKIES & STORAGE",title:"Politika e Cookies",intro:"Kjo faqe shpjegon cookies, localStorage dhe përmbajtjen e jashtme që mund të përdoret nga Lezha Turistike.",sections:[
["Çfarë përdor faqja","Nga implementimi aktual, Lezha Turistike përdor localStorage për të mbajtur preferencën Day/Night Mode dhe për të kujtuar në atë shfletues nëse një vend i Kulinarisë është vlerësuar. localStorage nuk është cookie, por është ruajtje lokale në pajisjen tuaj."],
["Cookies thelbësore","Infrastruktura teknike ose shërbimet që mundësojnë funksionimin dhe sigurinë e faqes mund të përdorin teknologji rreptësisht të nevojshme. Këto nuk përdoren nga ne për reklamim të personalizuar."],
["Analitika","Në implementimin e audituar aktualisht nuk kemi identifikuar Google Analytics ose Google Tag Manager. Nëse shtohen më vonë mjete analitike që kërkojnë pëlqim, kjo politikë dhe mekanizmi i pëlqimit do të përditësohen."],
["Përmbajtja e palëve të treta","Web GIS/ArcGIS dhe përmbajtje të tjera të jashtme mund të ngarkohen ose hapen nga faqja. Ofruesit e këtyre shërbimeve mund të përdorin cookies ose teknologji të ngjashme sipas politikave të tyre, të cilat ne nuk i kontrollojmë."],
["Si t’i menaxhoni","Mund të fshini localStorage dhe cookies nga cilësimet e shfletuesit. Fshirja e localStorage mund të rivendosë Day/Night Mode dhe kujtesën lokale të vlerësimeve. Bllokimi i teknologjive të palëve të treta mund të ndikojë në hartat ose përmbajtjen e integruar."],
["Përditësimet","Nëse shtojmë analytics, marketing, embeds të rinj ose teknologji të tjera jo-thelbësore, do të rishikojmë këtë politikë dhe, kur kërkohet, do të kërkojmë pëlqim përpara aktivizimit."]]}
},
en:{
privacy:{eyebrow:"PRIVACY",title:"Privacy Policy",intro:"This policy explains how Lezha Turistike handles information when you use the website.",sections:[
["Data and purpose","Visitors are not required to create an account. If you contact us by email, the information you send is used to respond and for the communication you requested. Hosting and technical infrastructure may process technical data such as IP address, request time, device information or similar data for security and operation."],
["Preferences and ratings","Day/Night Mode stores the selected theme locally in your browser. In Cuisine, the browser locally remembers that a place has been rated, while the 1–5 rating is sent to the website system and stored in Sanity to calculate the aggregate rating. This feature does not request a name or email."],
["External services","The website embeds or links to third-party services, including ArcGIS/Web GIS and links to websites, maps, social networks or scientific sources. When you open or interact with them, the relevant provider may process data under its own policies."],
["Retention and security","We aim to limit data to what is necessary for operation, security, communication and visitor-requested functions. Data is retained only as long as necessary for the relevant purpose or legal obligations."],
["Your rights","Depending on applicable law, you may request information, access, correction or deletion of personal data controlled by us, and object to or restrict processing where those rights apply."],
["Contact","For privacy questions or rights requests, contact: lezhaturistike@gmail.com. The formal identity of the website operator/controller will be added once officially determined."]]},
terms:{eyebrow:"TERMS",title:"Terms & Conditions",intro:"By using Lezha Turistike, you agree to these basic terms governing use of the website and its content.",sections:[
["Purpose","Lezha Turistike provides tourism, cultural, historical, archaeological, scientific and mapping information for information and promotional purposes."],
["Accuracy","We aim to keep information accurate and current, but opening hours, prices, contacts, admission conditions, locations and third-party information can change. Verify travel or booking information with the relevant provider."],
["Maps and Web GIS","Maps, coordinates, Web GIS applications and visualisations are informational and do not replace official, cadastral or legal documentation, professional navigation or instructions from authorities."],
["Intellectual property","Text, design, photographs, maps, data and materials may be protected by copyright or licences belonging to their authors, institutions and partners. Third-party materials remain the property of their respective rights holders."],
["External links","The website may link to ArcGIS, Google Maps, institutional websites, social networks and other resources. Lezha Turistike does not control their content, availability or policies."],
["Acceptable use","Do not use the website for technical interference, abuse of functions, unauthorised access attempts or uses that infringe the rights of others."],
["Changes","These terms may be updated when features, content or legal requirements change. The version published on this page is the current version."]]},
cookies:{eyebrow:"COOKIES & STORAGE",title:"Cookie Policy",intro:"This page explains cookies, localStorage and external content that may be used by Lezha Turistike.",sections:[
["What this website uses","In the current implementation, Lezha Turistike uses localStorage to remember the Day/Night Mode preference and whether a Cuisine place has already been rated in that browser. localStorage is not a cookie; it is local storage on your device."],
["Essential technologies","Technical infrastructure or services enabling website operation and security may use strictly necessary technologies. We do not use these for personalised advertising."],
["Analytics","In the implementation currently audited, we have not identified Google Analytics or Google Tag Manager. If consent-requiring analytics are added later, this policy and the consent mechanism will be updated."],
["Third-party content","Web GIS/ArcGIS and other external content may be loaded or opened from the website. These providers may use cookies or similar technologies under their own policies, which we do not control."],
["Managing storage","You can delete localStorage and cookies through your browser settings. Clearing localStorage may reset Day/Night Mode and the local rating memory. Blocking third-party technologies may affect maps or embedded content."],
["Updates","If we add analytics, marketing, new embeds or other non-essential technologies, we will review this policy and, where required, request consent before activation."]]}
}};
export type LegalContent={eyebrow:string;eyebrowEn:string;title:string;titleEn:string;intro:string;introEn:string;updated:string;updatedEn:string;sections:Array<{_key:string;heading:string;headingEn:string;body:string;bodyEn:string}>};
export default function LegalPage({locale="sq",kind,content}:{locale?:Locale;kind:Kind;content?:LegalContent}){const fallback=copy[locale][kind]; const x=content?{eyebrow:locale==="en"?content.eyebrowEn:content.eyebrow,title:locale==="en"?content.titleEn:content.title,intro:locale==="en"?content.introEn:content.intro,sections:content.sections.map(s=>[locale==="en"?s.headingEn:s.heading,locale==="en"?s.bodyEn:s.body])}:fallback;return <><LocaleHeader locale={locale}/><main id="home"><section className="section legal-page"><div className="legal-hero"><span className="overline">{x.eyebrow}</span><h1>{x.title}</h1><p>{x.intro}</p><small>{content?(locale==="en"?content.updatedEn:content.updated):(locale==="sq"?"Përditësuar: 22 shtator 2026":"Updated: 22 September 2026")}</small></div><div className="legal-content">{x.sections.map(([h,p])=><section key={h}><h2>{h}</h2><p>{p}</p></section>)}<div className="legal-note">{locale==="sq"?<>Për pyetje: <a href="mailto:lezhaturistike@gmail.com">lezhaturistike@gmail.com</a>. Shih gjithashtu <Link href="/privacy">Privatësinë</Link>, <Link href="/terms">Kushtet</Link> dhe <Link href="/cookies">Cookie Policy</Link>.</>:<>Questions: <a href="mailto:lezhaturistike@gmail.com">lezhaturistike@gmail.com</a>. See also <Link href="/en/privacy">Privacy</Link>, <Link href="/en/terms">Terms</Link> and <Link href="/en/cookies">Cookie Policy</Link>.</>}</div></div></section></main><BackToTop locale={locale}/><SiteFooter locale={locale}/></>}