import Link from "next/link";

type Locale="sq"|"en";
const labels={
 sq:{explore:"Eksploro",connect:"Le të lidhemi",info:"Për informacion dhe bashkëpunime.",location:"LEZHË · SHQIPËRI",address:"Rruga e Kalasë",country:"Lezhë, Shqipëri",contact:"Na kontakto",motto:"Njih historinë. Eksploro natyrën. Zbulo Lezhën.",desc:"Një qytet për t’u zbuluar.",desc2:"Histori, natyrë dhe trashëgimi kulturore, të lidhura përmes hartave dhe rrëfimeve.",dest:"Destinacione",history:"Histori & Arkeologji",arch:"Arkeologji",science:"Punime shkencore",food:"Kulinari",partners:"Partnerët",gallery:"Galeri",privacy:"Privatësia",terms:"Kushtet",cookies:"Cookie Policy"},
 en:{explore:"Explore",connect:"Let's connect",info:"For information and collaboration.",location:"LEZHË · ALBANIA",address:"Castle Road",country:"Lezhë, Albania",contact:"Contact us",motto:"Know the history. Explore nature. Discover Lezhë.",desc:"A city waiting to be discovered.",desc2:"History, nature and cultural heritage connected through maps and stories.",dest:"Destinations",history:"History & Archaeology",arch:"Archaeology",science:"Scientific research",food:"Cuisine",partners:"Partners",gallery:"Gallery",privacy:"Privacy",terms:"Terms",cookies:"Cookie Policy"}
};
export default function SiteFooter({locale="sq"}:{locale?:Locale}){
 const t=labels[locale], p=(x:string)=>locale==="en"?"/en"+x:x;
 return <footer className="site-footer" aria-label={locale==="en"?"Page footer":"Fundi i faqes"}>
  <div className="footer-main"><Link href={p("")||"/"} className="logo" aria-label="Lezha Turistike"><span className="logo-mark logo-castle" aria-hidden="true"><i></i><i></i><i></i></span><span>LEZHA<br/><b>TURISTIKE</b></span></Link><p>{t.desc}<br/>{t.desc2}</p><span className="footer-location">{t.location}</span></div>
  <nav className="footer-navigation" aria-label={locale==="en"?"Footer navigation":"Navigimi në fund të faqes"}><h2>{t.explore}</h2><div className="footer-links"><Link href={p("/destinacione")}>{t.dest}</Link><Link href={p("/histori")}>{t.history}</Link><Link href={p("/webgis")}>Web GIS</Link><Link href={p("/shkenca")}>{t.science}</Link><Link href={p("/kulinari")}>{t.food}</Link><Link href={`${p("/shkenca")}#partneret`}>{t.partners}</Link><Link href={p("/galeri")}>{t.gallery}</Link></div></nav>
  <div className="footer-contact"><h2>{t.connect}</h2><p>{t.info}</p><a className="footer-email" href="mailto:lezhaturistike@gmail.com">lezhaturistike@gmail.com <span className="arrow-icon" aria-hidden="true">↗</span></a><p>{t.address}<br/>{t.country}</p><Link className="footer-contact-link" href={p("/kontakt")}>{t.contact} <span className="arrow-icon" aria-hidden="true">↗</span></Link></div>
  <div className="footer-bottom"><span className="footer-credit">© 2026 Lezha Turistike. <span aria-hidden="true">·</span> <a href="https://lindimaps.com/" target="_blank" rel="noopener noreferrer" aria-label="LINDIMAPS Spatial Intelligence"><span className="footer-credit-label">Developed by</span> <span className="footer-lindimaps-wordmark"><b>LINDI</b><i>MAPS</i></span></a></span><div className="footer-legal"><Link href={p("/privacy")}>{t.privacy}</Link><Link href={p("/terms")}>{t.terms}</Link><Link href={p("/cookies")}>{t.cookies}</Link></div><span>{t.motto}</span></div>
 </footer>
}
